// Shared list of colleges for dropdowns and filters
// Source: user-provided curated list (Delhi/NCR)

const colleges = [
  'Maharaja Agrasen Institute of Technology (MAIT)',
  'Indian Institute of Technology Delhi (IIT Delhi)',
  'Delhi Technological University (DTU)',
  'Netaji Subhas University of Technology (NSUT)',
  'Indraprastha Institute of Information Technology Delhi (IIIT Delhi)',
  'Jamia Millia Islamia - Faculty of Engineering and Technology',
  'Guru Tegh Bahadur Institute of Technology (GTBIT)',
  'Bharati Vidyapeeth’s College of Engineering',
  'Bhagwan Parshuram Institute of Technology (BPIT)',
  'Maharaja Surajmal Institute of Technology (MSIT)',
  'Bhaskaracharya College of Applied Sciences',
  'Acharya Narendra Dev College',
  'Cluster Innovation Centre (CIC), University of Delhi',
  'Faculty of Technology, University of Delhi',
  'Ambedkar Institute of Technology',
  'School of Planning and Architecture (SPA), Delhi',
  'Indira Gandhi Delhi Technical University for Women (IGDTUW)',
  'Amity School of Engineering & Technology, Delhi',
  'Jamia Hamdard - School of Engineering Science & Technology',
  'Guru Premsukh Memorial College of Engineering',
  'National Institute of Technology Delhi (NIT Delhi)',
  'University School of Biotechnology',
  'University School of Chemical Technology',
  'University School of Information Technology',
  'University School of Automation and Robotics',
  'Dr. Akhilesh Das Gupta Institute of Professional Studies',
  'CBP Government Engineering College',
  'Govind Ballabh Pant Engineering College',
  'Delhi Institute of Tool Engineering',
  'Sushant School of Art and Architecture',
  'TVB School of Habitat Studies',
  'Vastu Kala Academy',
  'HMR Institute of Technology & Management',
  'Northern India Engineering College',
  'Fairfield Institute of Management and Technology',
  'Shri Ram College of Commerce (SRCC)',
  'Hindu College',
  'Hansraj College',
  'St. Stephen’s College',
  'Miranda House',
  'Lady Shri Ram College for Women (LSR)',
  'Ramjas College',
  'Kirori Mal College',
  'Daulat Ram College',
  'Indraprastha College for Women (IP College)',
  'Sri Venkateswara College',
  'Atma Ram Sanatan Dharma College (ARSD)',
  'Gargi College',
  'Maitreyi College',
  'Delhi College of Arts & Commerce (DCAC)'
];

export default colleges;


